// Code generated by "stringer -type=lexItemType"; DO NOT EDIT.

package sqlread

import "fmt"

const _lexItemType_name = "TIllegalTEofTSemiTCommaTCommentTNullTStringTNumberTIdentifierTDropTableFullStmtTLockTableFullStmtTUnlockTablesFullStmtTSetFullStmtTLParenTRParenTCreateTableTCreateTableDetailTCreateTableExtraTColumnTypeTColumnSizeTColumnEnumValTColumnDetailsTInsertIntoTInsertValuesTInsertRow"

var _lexItemType_index = [...]uint16{0, 8, 12, 17, 23, 31, 36, 43, 50, 61, 79, 97, 118, 130, 137, 144, 156, 174, 191, 202, 213, 227, 241, 252, 265, 275}

func (i lexItemType) String() string {
	if i >= lexItemType(len(_lexItemType_index)-1) {
		return fmt.Sprintf("lexItemType(%d)", i)
	}
	return _lexItemType_name[_lexItemType_index[i]:_lexItemType_index[i+1]]
}
