// Code generated by "stringer -type=lexItemType"; DO NOT EDIT.

package sqlread

import "fmt"

const _lexItemType_name = "TIllegalTEofTSemiTCommaTCommentTDelimTNullTStringTNumberTIdentifierTDropTableFullStmtTLockTableFullStmtTUnlockTablesFullStmtTSetFullStmtTLParenTRParenTCreateTableTCreateTableDetailTcreateTableExtraDetailTColumnTypeTColumnSizeTColumnEnumValTColumnDetailsTInsertIntoTInsertValuesTIntpSelectTIntpStarTIntpFromTIntpIntoOutfileTIntpShowTablesTIntpShowColumnsTIntpQuit"

var _lexItemType_index = [...]uint16{0, 8, 12, 17, 23, 31, 37, 42, 49, 56, 67, 85, 103, 124, 136, 143, 150, 162, 180, 203, 214, 225, 239, 253, 264, 277, 288, 297, 306, 322, 337, 353, 362}

func (i lexItemType) String() string {
	if i >= lexItemType(len(_lexItemType_index)-1) {
		return fmt.Sprintf("lexItemType(%d)", i)
	}
	return _lexItemType_name[_lexItemType_index[i]:_lexItemType_index[i+1]]
}
