on: [ push, pull_request ]
name: CI
jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...
